### ISSUE TITLE
Can not withdraw my deposited fund

### ISSUE THREAD

**Issue by luantranminh** [jet-lab/jet-v1#3] opened 2021-09-13 20:51 UTC
401 $SOL deposited
![image](https://user-images.githubusercontent.com/25551568/133154414-f23882c5-7105-4fef-879c-d0de429c1432.png)

![image](https://user-images.githubusercontent.com/25551568/133154517-53d490e3-1fe5-457b-931e-51c4763b49a5.png)

Console log
![image](https://user-images.githubusercontent.com/25551568/133154377-035091ef-d491-422e-b2e0-9771ce139b0f.png)

transaction: https://explorer.solana.com/tx/2PDjwxHBs4LgQsB72nDs2mYwukS5vVwuspqRp6iEyXCXFE843ahhtrxkxCGaUKXkcRaKGoVQRGtePv3oumW6LPaL?cluster=devnet

**Comment by suscd** [comment] 2021-09-14 01:51
Duplicate of #6

Should be fixed

**Closed by suscd** 2021-09-14 01:51 UTC
